from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence

from .io import atomic_write_text, normalize_sha256


def markdown_escape(value: Any) -> str:
    if value is None or value == "":
        return "—"

    return (
        str(value)
        .replace("|", r"\|")
        .replace("\n", " ")
    )


def short_hash(value: Any) -> str:
    normalized = normalize_sha256(value)
    return (
        f"`{normalized[:12]}…`"
        if normalized
        else "—"
    )


def render_readme(
    records: Sequence[Mapping[str, Any]],
) -> str:
    lines = [
        "# Model licenses",
        "",
        "> Generated by `uv run -m licenses report`.",
        "> Do not edit the asset table manually.",
        "",
        "## Assets",
        "",
        "| Asset | Type | Provider | Version | Local SHA-256 | Hash check | Review | Commercial output |",
        "|---|---|---|---|---|---|---|---|",
    ]

    for record in sorted(
        records,
        key=lambda item: str(item.get("asset_id")),
    ):
        identity = record.get("identity") or {}
        source = record.get("source") or {}
        file_info = record.get("file") or {}
        review = record.get("review") or {}
        permissions = review.get("permissions") or {}

        name = (
            identity.get("name")
            or record.get("asset_id")
        )
        url = source.get("canonical_url")

        asset_cell = (
            f"[{markdown_escape(name)}]({url})"
            if isinstance(url, str)
            and url.startswith(("https://", "http://"))
            else markdown_escape(name)
        )

        lines.append(
            "| "
            + " | ".join([
                asset_cell,
                markdown_escape(record.get("asset_type")),
                markdown_escape(source.get("provider")),
                markdown_escape(identity.get("version_name")),
                short_hash(file_info.get("sha256")),
                markdown_escape(file_info.get("verification")),
                markdown_escape(review.get("status")),
                markdown_escape(
                    permissions.get(
                        "generated_output_commercial_use",
                        "unknown",
                    )
                ),
            ])
            + " |"
        )

    lines.extend([
        "",
        "## Commands",
        "",
        "```bash",
        "uv run -m licenses sync",
        "uv run -m licenses verify",
        "uv run -m licenses report",
        "```",
        "",
        "Human-maintained files:",
        "",
        "- `licenses/registry.toml`",
        "- `licenses/reviews/*.toml`",
        "- `licenses/evidence/**` when evidence is retained",
        "",
        "Generated files:",
        "",
        "- `licenses/models/*.json`",
        "- `licenses/README.md`",
        "",
    ])

    return "\n".join(lines)


def write_report(
    readme_path: Path,
    records: Sequence[Mapping[str, Any]],
) -> None:
    atomic_write_text(
        readme_path,
        render_readme(records),
    )
