from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence

from .io import (
    atomic_write_text,
    normalize_sha256,
    normalize_weights_sha256,
)


def markdown_escape(value: Any) -> str:
    if value is None or value == "":
        return "—"

    return (
        str(value)
        .replace("|", r"\|")
        .replace("\n", " ")
    )


def hash_cell(
    local: Any,
    provider: Any,
    expected: Any = None,
    *,
    weights: bool = False,
) -> str:
    normalize = normalize_weights_sha256 if weights else normalize_sha256
    for value, label in (
        (local, ""),
        (provider, "source"),
        (expected, "pinned"),
    ):
        normalized = normalize(value)
        if normalized:
            shown = (
                normalized
                if len(normalized) <= 12
                else f"{normalized[:12]}…"
            )
            suffix = f" ({label})" if label else ""
            return f"`{shown}`{suffix}"
    return "—"


def render_readme(
    records: Sequence[Mapping[str, Any]],
) -> str:
    lines = [
        "# Model licenses",
        "",
        "> Generated by `uv run python -m licenses report`.",
        "> Do not edit the asset table manually.",
        "",
        "## Assets",
        "",
        "| Asset | Type | Provider | Version | File SHA-256 | Weights SHA-256 | Identity check | Review | Commercial output |",
        "|---|---|---|---|---|---|---|---|---|",
    ]

    for record in sorted(
        records,
        key=lambda item: str(item.get("asset_id")),
    ):
        identity = record.get("identity") or {}
        source = record.get("source") or {}
        file_info = record.get("file") or {}
        review = record.get("review") or {}
        permissions = review.get("permissions") or {}

        name = (
            identity.get("name")
            or record.get("asset_id")
        )
        url = source.get("canonical_url")

        asset_cell = (
            f"[{markdown_escape(name)}]({url})"
            if isinstance(url, str)
            and url.startswith(("https://", "http://"))
            else markdown_escape(name)
        )

        lines.append(
            "| "
            + " | ".join([
                asset_cell,
                markdown_escape(record.get("asset_type")),
                markdown_escape(source.get("provider")),
                markdown_escape(identity.get("version_name")),
                hash_cell(
                    file_info.get("sha256"),
                    file_info.get("provider_sha256"),
                    file_info.get("expected_sha256"),
                ),
                (
                    "n/a"
                    if str(file_info.get("filename", "")).lower().endswith(".pth")
                    else hash_cell(
                        file_info.get("weights_sha256"),
                        file_info.get("provider_weights_sha256"),
                        weights=True,
                    )
                ),
                markdown_escape(file_info.get("verification")),
                markdown_escape(review.get("status")),
                markdown_escape(
                    permissions.get(
                        "generated_output_commercial_use",
                        "unknown",
                    )
                ),
            ])
            + " |"
        )

    lines.extend([
        "",
        "## Hash semantics",
        "",
        "- `File SHA-256` identifies exact bytes. Local values are preferred; `(source)` comes from the distributor and `(pinned)` is a reviewed expected digest.",
        "- `Weights SHA-256` is safetensors `modelspec.hash_sha256` and identifies tensor data even when header padding differs.",
        "- Provider identity checks prefer the weights hash. Civitai `AutoV3` values are recorded and compared as 12-character prefixes.",
        "- A missing weights hash remains unknown; `n/a` means the non-safetensors format does not carry ModelSpec metadata.",
        "",
        "## Local model verification",
        "",
        "Copy `.env.example` to the untracked `.env`, set `CARDGEN_COMFYUI_MODELS_DIR` to the absolute ComfyUI `models` directory, then run `sync` without `--skip-hash`.",
        "The registry's `models/...` paths are resolved below that directory; model files are read in place and are not copied into this repository.",
        "",
        "## Commands",
        "",
        "```bash",
        "uv run python -m licenses sync",
        "uv run python -m licenses verify",
        "uv run python -m licenses report",
        "```",
        "",
        "Human-maintained files:",
        "",
        "- `licenses/registry.toml`",
        "- `licenses/reviews/*.toml`",
        "- `licenses/evidence/**` when evidence is retained",
        "",
        "Generated files:",
        "",
        "- `licenses/models/*.json`",
        "- `licenses/README.md`",
        "",
    ])

    return "\n".join(lines)


def write_report(
    readme_path: Path,
    records: Sequence[Mapping[str, Any]],
) -> None:
    atomic_write_text(
        readme_path,
        render_readme(records),
    )
